version: '2'

services:
  warodai:
    image: warodai
    build: ./
    ports:
      - "80:80"
    volumes:
      - /d/Dev/nbyars/warodai.ru/public:/var/www/html
      - /d/Dev/nbyars/warodai.ru/vendor:/var/www/vendor
    network_mode: host