version: '2'

services:
  warodai:
    image: warodai
    build: ./
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
      - ./etc:/var/www/etc
      - ./vendor:/var/www/vendor
      - ./workers:/var/www/workers
      - ./repos:/var/www/repos
  mongo:
    image: mongo:3.4