version: '2'

services:
  warodai:
    image: warodai
    build: ./
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
      - ./etc:/var/www/etc
      - ./vendor:/var/www/vendor
      - ./workers:/var/www/workers
      - ./repos:/var/www/repos
    network_mode: host
  mongo:
    image: mongo:3.4
    volumes:
        - /home/naken/data/mongo/local:/data/db
    network_mode: "host"